Trails2012_Backup_2012.02.16_09.02.31/Controllers/TrailController.cs
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.IO;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Trails2012.DataAccess;
using Trails2012.Domain;

namespace Trails2012.Controllers
{   
    public class TrailController : Controller
    {
        private readonly IRepository _repository;

        [ImportingConstructor]
        public TrailController(IRepository repository)
        {
            _repository = repository;
        }


        //
        // GET: /Trail/

        public ViewResult Index()
        {
            return View(new List<Trail>(_repository.List<Trail>()));
        }

        //
        // GET: /Trail/Details/5

        public ViewResult Details(int id)
        {
            ViewBag.IsReadOnly = true;
            return View(_repository.GetById<Trail>(id));
        }

        //
        // GET: /Trail/Create

        public ActionResult Create()
        {
            Trail newTrail = new Trail();
			ViewBag.PossibleLocations = _repository.List<Location>();
            ViewBag.PossibleTrailTypes = _repository.List<TrailType>();
            ViewBag.PossibleDifficulties = _repository.List<Difficulty>();
            return View(newTrail);
        } 

        //
        // POST: /Trail/Create

        // Andy - set ValidateInput(false) so that the Notes editor can set formatting tags without causing the 
        // "A potentially dangerous Request.Form value was detected from the client" error.
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(Trail trail, HttpPostedFileBase file)
        {
            if (ModelState.IsValid) 
            {

                BinaryReader binaryReader = new BinaryReader(file.InputStream); 
                byte[] byteArray = binaryReader.ReadBytes(file.ContentLength);
                trail.Image = byteArray;

                // see Comment 1
                if (trail.DifficultyId.HasValue)
                {
                    Difficulty difficulty = _repository.GetById<Difficulty>(trail.DifficultyId.Value);
                    trail.Difficulty = difficulty;
                }
                Location location = _repository.GetById<Location>(trail.LocationId);
                trail.Location = location;
                TrailType trailType = _repository.GetById<TrailType>(trail.TrailTypeId);
                trail.TrailType = trailType;


                _repository.Insert(trail);
                _repository.SaveChanges();
                return RedirectToAction("Index");
            }

            //=================================
            var image = WebImage.GetImageFromRequest();

            if (image != null)
            {
                if (image.Width > 500)
                {
                    image.Resize(500, ((500 * image.Height) / image.Width));
                }
             //newImage.MimeType = image.ContentType;
           //     file.ContentType
 

                var binaryReader = new BinaryReader(file.InputStream);
                //newImage.Data = 
                byte[] byteArray =  binaryReader.ReadBytes(file.ContentLength);
                binaryReader.Close();
 
                //var filename = Path.GetFileName(image.FileName);
                //image.Save(Path.Combine("../Uploads/Images", filename));
                //filename = Path.Combine("~/Uploads/Images", filename);
                //string ImageUrl = Url.Content(filename);
                //string ImageAltText = image.FileName.Substring(0, image.FileName.Length - 4);

            }
            //=================================

            ViewBag.PossibleLocations = _repository.List<Location>();
            ViewBag.PossibleTrailTypes = _repository.List<TrailType>();
            ViewBag.PossibleDifficulties = _repository.List<Difficulty>();
            return View();
        }
        
        //
        // GET: /Trail/Edit/5
 
        public ActionResult Edit(int id)
        {
            ViewBag.PossibleLocations = _repository.List<Location>();
            ViewBag.PossibleTrailTypes = _repository.List<TrailType>();
            ViewBag.PossibleDifficulties = _repository.List<Difficulty>();
            Trail trail = _repository.GetById<Trail>(id);
            return View(trail);
        }

        //
        // POST: /Trail/Edit/5
        // Andy - set ValidateInput(false) so that the Notes editor can set formatting tags without causing the 
        // "A potentially dangerous Request.Form value was detected from the client" error.
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Trail trail, HttpPostedFileBase file)
        {
            // Get the trail data back from the database and only then populate it from the model, 
            // because the form does not contain every piece of information about the entity;
            // specifically, it is missing the Image
            Trail savedTrail = _repository.GetById<Trail>(trail.Id);
            if (ModelState.IsValid)
            {
                UpdateModel(savedTrail);

                if (file != null)
                {
                    BinaryReader binaryReader = new BinaryReader(file.InputStream);
                    byte[] byteArray = binaryReader.ReadBytes(file.ContentLength);
                    savedTrail.Image = byteArray;
                }

                // see Comment 1
                if (trail.DifficultyId.HasValue)
                {
                    Difficulty difficulty = _repository.GetById<Difficulty>(trail.DifficultyId.Value);
                    trail.Difficulty = difficulty;
                }
                else
                    trail.Difficulty = null;
                if (trail.Location == null || trail.Location.Id != trail.LocationId)
                {
                    Location location = _repository.GetById<Location>(trail.LocationId);
                    trail.Location = location;
                }
                if (trail.TrailType == null || trail.TrailType.Id != trail.TrailTypeId)
                {
                    TrailType trailType = _repository.GetById<TrailType>(trail.TrailTypeId);
                    trail.TrailType = trailType;
                }


                _repository.Update(savedTrail);
                _repository.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PossibleLocations = _repository.List<Location>();
            ViewBag.PossibleTrailTypes = _repository.List<TrailType>();
            ViewBag.PossibleDifficulties = _repository.List<Difficulty>();
            return View();
        }

        //
        // GET: /Trail/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(_repository.GetById<Trail>(id));
        }

        //
        // POST: /Trail/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _repository.Delete<Trail>(id);
            _repository.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult ShowImage(int trailId)
        {
            Trail trail = _repository.GetById<Trail>(trailId);
            if (trail == null || trail.Image == null) return null;
            return File(trail.Image, "image/jpg");
        }


    }
}

// _Comment 1_
// Andy - The foreign keys (LocationId, etc) have been updated from the form.
// Assign the objects - this step is only necessary if using the current NHib reprository.
// (The current EF repository is mapped to work with the foreign keys such as LocationId directly, 
// but NHib works through the related objects)

Trails2012_Backup_2012.02.16_09.02.31/Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Telerik.Web.Mvc;
using Trails2012.DataAccess;
using Trails2012.Domain;

namespace Trails2012.Controllers
{
    public class TripController : Controller
    {
        private List<Person> _persons;

        private readonly IRepository _repository;
        //private List<Region> _regions;

        [ImportingConstructor]
        public TripController(IRepository repository)
        {
            _repository = repository;
        }


        //
        // GET: /Trip/
        public ActionResult Index(string searchTerm)
        {
            //ViewData["regions"] = _regions;
            List<Trip> trips;
            if (string.IsNullOrEmpty(searchTerm))
                trips = new List<Trip>(_repository.ListIncluding<Trip>(t => t.Persons, t => t.Trail));
            else
            {
                trips =
                    new List<Trip>(
                        _repository.ListIncluding<Trip>(t => t.Persons, t => t.Trail).Where(
                            t => t.Trail.Name.ToUpper().Contains(searchTerm.ToUpper())));
                ViewData["SearchTerm"] = searchTerm;
            }
            return View(trips);
        }

        //[GridAction]
        //public ActionResult Search(string searchTerm)
        //{
        //    List<Trip> trips;
        //    if (string.IsNullOrEmpty(searchTerm))
        //        trips = new List<Trip>(_repository.ListIncluding<Trip>(t => t.Persons, t => t.Trail));
        //    else
        //    {
        //        trips =
        //            new List<Trip>(
        //                _repository.ListIncluding<Trip>(t => t.Persons, t => t.Trail).Where(
        //                    t => t.Trail.Name.ToUpper().Contains(searchTerm.ToUpper())));
        //        ViewData["SearchTerm"] = searchTerm;
        //    }
        //    return View("Index", trips);
        //}

        //
        // GET: /Trip/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Trip/Create

        public ActionResult Create()
        {
            Trip newTrip = new Trip();
            newTrip.Persons = new List<Person>();
            ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
            ViewBag.PossibleTrails = _repository.List<Trail>();
            PopulatePersons();

            return View(newTrip);
        } 

        //
        // POST: /Trip/Create

        [HttpPost]
        public ActionResult Create(Trip trip, string personidlist)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    TransportType transportType = _repository.GetById<TransportType>(trip.TransportTypeId);
                    trip.TransportType = transportType;
                    Trail trail = _repository.GetById<Trail>(trip.TrailId);
                    trip.Trail = trail;

                    _repository.Insert(trip);

                    if (!string.IsNullOrEmpty(personidlist))
                    {
                        if (trip.Persons == null)
                            trip.Persons = new List<Person>();
                        string[] personIdArray = personidlist.Split(new[] {','});
                        foreach (string value in personIdArray)
                        {
                            int personId = Convert.ToInt32(value);
                            Person person = _repository.GetById<Person>(personId);
                            if(person != null)
                            {
                                trip.Persons.Add(person);
                            }
                        }
                    }

                    _repository.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
                ViewBag.PossibleTrails = _repository.List<Trail>();
                PopulatePersons();
                return View();

            }
            catch
            {
                ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
                ViewBag.PossibleTrails = _repository.List<Trail>();
                PopulatePersons();
                return View();
            }
        }

        //
        // GET: /Trip/Edit/5
 
        public ActionResult Edit(int id)
        {
            ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
            ViewBag.PossibleTrails = _repository.List<Trail>();

            //Trip trip = _repository.GetById<Trip>(id);
            Trip trip = _repository.Get<Trip>(t => t.Id.Equals(id), 
                null, // order by
                new Expression<Func<Trip, object>>[]
                    {
                        (t => t.Persons)
                    }) // include
                    .FirstOrDefault();

            PopulatePersons(trip.Persons.ToList());

            return View(trip);
        }

        //
        // POST: /Trip/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, Trip trip, List<Person> Persons)
        {
            try
            {
                Trip savedTrip = _repository.GetById<Trip>(trip.Id);
                if (ModelState.IsValid)
                {
                    UpdateModel(savedTrip);

                    if (trip.TransportType == null || trip.TransportType.Id != trip.TransportTypeId)
                    {
                        TransportType transportType = _repository.GetById<TransportType>(trip.TransportTypeId);
                        trip.TransportType = transportType;
                    }
                    if (trip.Trail == null || trip.Trail.Id != trip.TrailId)
                    {
                        Trail trail = _repository.GetById<Trail>(trip.TrailId);
                        trip.Trail = trail;
                    }

                    _repository.Update(savedTrip);
                    _repository.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
                    ViewBag.PossibleTrails = _repository.List<Trail>();
                    PopulatePersons();
                    return View();
                }
            }
            catch
            {
                ViewBag.PossibleTransportTypes = _repository.List<TransportType>();
                ViewBag.PossibleTrails = _repository.List<Trail>();
                PopulatePersons();
                return View();
            }
        }

        private void PopulatePersons(IList<Person> peopleToOmit = null)
        {
            if (peopleToOmit == null)
                _persons = new List<Person>(_repository.List<Person>());
            else
            {
                _persons = new List<Person>(_repository.List<Person>()).Except(peopleToOmit).ToList();
            }

            ViewData["persons"] = _persons;
        }

        [GridAction]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Trip trip = _repository.GetById<Trip>(id);
            _repository.Delete(trip);
            _repository.SaveChanges();
           return RedirectToAction("Index");
        }
   
        public JsonResult GetTrailNames(string searchTerm, int maxResults)
        {
             IEnumerable<Trail> trails = _repository.List<Trail>().Where(t => t.Name.ToUpper().Contains(searchTerm.ToUpper())).Take(10).ToList();
             List<object> results = new List<object>();
            foreach (Trail trail in trails)
            {
                results.Add(new {Id = trail.Id, Name = trail.Name});
            }

            return Json(results);           
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public string AddPersonToTrip(string id, string personId, List<string> personIds)
        {
            if (string.IsNullOrEmpty(id))
                return "Invalid id. Please press back or enable JavaScript.";

            int pId = Convert.ToInt32(personId);
            int tripId = Convert.ToInt32(id);

            Person personToAdd = _repository.GetById<Person>(pId);

            Trip trip = _repository.Get<Trip>(t => t.Id.Equals(tripId),
                                              null, // order by
                                              new Expression<Func<Trip, object>>[]
                                                  {
                                                      (t => t.Persons)
                                                  }) // include
                .FirstOrDefault();

            if (trip == null) return "Trip not found";

            if (trip.Persons.Where(p => p.Id == pId).Count() == 0)
            {
                trip.Persons.Add(personToAdd);
                _repository.Update(trip);
                _repository.SaveChanges();
            }
            return string.Format("Successfully added {0}.", personToAdd.FirstName);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public string RemovePersonFromTrip(string id, string personId, List<string> personIds)
        {
            if (string.IsNullOrEmpty(id))
                return "Invalid id. Please press back or enable JavaScript."; //Add to cart logic            

            int pId = Convert.ToInt32(personId);
            int tripId = Convert.ToInt32(id);

            Person personToRemove = _repository.GetById<Person>(pId);

            Trip trip = _repository.Get<Trip>(t => t.Id.Equals(tripId),
                                              null, // order by
                                              new Expression<Func<Trip, object>>[]

Trails2012_Backup_2012.02.16_09.02.31/Views/Trip/Create.cshtml
@model Trails2012.Domain.Trip

@{
    ViewBag.Title = "Create Trip";
}

    <style type="text/css">
		#sortable1, #sortable2, #sortable3 { list-style-type: none; margin: 0; padding: 0; margin-right: 10px; background: #eee; padding: 5px; width: 143px;}
	    #sortable1 li, #sortable2 li, #sortable3 li { margin: 5px; padding: 5px; font-size: 1.2em; width: 120px; }
        #personsTable {margin: 10px; }
    </style>

    <script type="text/javascript">

        $(function () {

            $("#sortable1, #sortable2").sortable({
                connectWith: ".connectedSortable",                
                stop: function (event, ui) {
                       var personsontrip = $("#sortable1").sortable('toArray');
                        //debugger;                    
                        $('#personidlist').val(personsontrip);                        
                }

            }).disableSelection();
        });

    </script>


@using (Html.BeginForm("Create", "Trip", FormMethod.Post, new { enctype = "multipart/form-data"  }))
 {
     @Html.ValidationSummary(true)
     <fieldset>
         <legend>Trip</legend>

         <div class="result"></div>
         <input type="hidden" id="personidlist" name="personidlist" ></input>
         <div>

		@Html.Partial("_CreateOrEdit", Model)

         <fieldset>
           <legend>People on the Trip</legend>
             <table id="personsTable">
                <tr>
                    <th>People on Trip</th>
                    <th>Select people</th>
                 </tr>
                 <tr>
                     <td>
                         <ul id="sortable1" class="connectedSortable">

                                @if (Model != null && Model.Persons != null) {
                                    foreach (var person in Model.Persons)
                                     {
                                         <li class="ui-state-default" id="@person.Id">@Html.DisplayFor(model => person.FirstName)</li>
                                     }
                                }
                         </ul>
                     </td>
                     <td>
                         <ul id="sortable2" class="connectedSortable">
                          @foreach (var person in (List<Trails2012.Domain.Person>)ViewData["persons"])
                             {
                                 <li class="ui-state-highlight" id="@person.Id">@Html.DisplayFor(model => person.FirstName)</li>
                             }
                          </ul>
                     </td>
                 </tr>
             </table>
             </fieldset>    
         </div>

     </fieldset>

     <p>
         <input type="submit" value="Save" />
     </p>
 }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Trails2012_Backup_2012.02.16_09.02.31/Views/Trip/Details.cshtml
@model Trails2012.Domain.Trip

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

Trails2012_Backup_2012.02.16_09.02.31/Views/Trip/Index.cshtml
@using Telerik.Web.Mvc.UI

@model IEnumerable<Trails2012.Domain.Trip>

@{
    ViewBag.Title = "Trips";
}

<h2>Trips</h2>


 <script type="text/javascript">


     $(function () {

         $('#searchTerm').autocomplete({
             source: function (request, response) {
                 $.ajax({
                     url: '@Url.Action("GetTrailNames", "Trip")', type: "POST", datatype: "json",
                     data: { searchTerm: request.term, maxResults: 10 },
                     success: function (data) {
                         //debugger;
                         response($.map(data, function (item) {
                             return { label: item.Name, value: item.Name, id: item.Id };
                         }));
                     },
//                     parse: function (data) {
//                         debugger;
//                         var rows = new Array();
//                         for (var i = 0; i < data.length; i++) {
//                             rows[i] = { data: data[i], value: data[i].Name, result: data[i].Name };
//                         }
//                         return rows;
//                     },
//                     formatItem: function (row) {
//                         debugger;
//                         return row.Name;
//                     },
                     delay: 40, autofill: true, selectFirst: false, highlight: false, multiple: true, multipleSeparator: ";"
                 });
             }
         });

     });


  </script>


  @using (Html.BeginForm("Index","Trip")) {
    <fieldset>
       <legend>Search Trips</legend>
       @*TODO: we could add ability to search by people and dates*@
      <input type="text" name="searchTerm" id="searchTerm" size="10" maxlength ="30" value="@ViewData["SearchTerm"]" />
      <input type ="submit" value="Search" />
    </fieldset>
      }

@(Html.Telerik().Grid(Model)
                                       .Name("TripGrid")
                                       //.ToolBar(commands => commands.Insert())
                                       .Columns(columns =>
                                                    {
                                                        columns.Bound(region => region.Date).Title("Sort by date");
                                                        columns.Bound(region => region.Trail.Name).Title("Sort by trail name");           
                                                    })

                                       .DataBinding(dataBinding => 
                                                                    dataBinding.Server()
                                                                       .Insert("Create", "Trip")
                                                                       .Update("Edit", "Trip")
                                                                       .Delete("Delete", "Trip")
                                                                       .Select("Index", "Trip", new { searchTerm = (string)ViewData["SearchTerm"] })
                                                                       
                                       )
                                       .Pageable()
                                       .Sortable()
                                       .DataKeys(keys => keys.Add(trip => trip.Id))
                                       .RowTemplate(grid => @<text>
                                                                 <div class="trip-details">
                                                                     @if (item.Trail.Image != null)
                                                                     {
                                                                         <img class = 'TrailImageSmall' src='@Url.Action("ShowImage", "Trail", new { TrailId = item.Trail.Id })' alt="Image of @Html.DisplayFor(model => item.Trail.Name)" />
                                                                     }
                                                                     <h3>@item.Trail.Name</h3>
                                                                     <dl>
                                                                         <dt>Date:</dt><dd>@item.Date.ToString("d")</dd>
                                                                         <dt>People</dt><dd>@item.PersonsSummary</dd>
                                                                     </dl>                 
                                                                     <div class="commands">
                                                                         @Html.ActionLink("Edit","Edit", new { id = item.Id })
                                                                         @*@grid.EditButton(item)*@

                                                                         @grid.DeleteButton(item)                                    
                                                                     </div>               
                                                                 </div>
                                                             </text>))


<p>
    @Html.ActionLink("Create New", "Create")
</p>







@*@(Html.Telerik().Grid(Model)
            .Name("TripGrid")
    .ToolBar(commands => commands.Insert())
    .DataKeys(keys => keys.Add(trip => trip.Id))
            .Columns(columns =>
                         {
                             columns.Bound(region => region.Date);
                             columns.Bound(region => region.Trail.Name);
                             columns.Bound(region => region.Trail.Image);
                             columns.Bound(region => region.PersonsSummary);
                             columns.Command(commands =>
                                                 {
                                                     commands.Delete();
                                                     commands.Edit();
                                                     commands.Select();
                                                 }
                                 );
                         })
                         .RowTemplate(grid => @<text>
                            <div class="trip-details">
                                 @if (item.Trail.Image != null)
                                {
                                    <img class = 'TrailImageSmall' src='@Url.Action("ShowImage", "Trail", new {TrailId = item.Trail.Id})' alt="Image of @Html.DisplayFor(model => item.Trail.Name)" />
                                }
                                <h3>@item.Trail.Name</h3>
                                <dl>
                                    <dt>Date:</dt><dd>@item.Date</dd>
                                    <dt>People</dt><dd>@item.PersonsSummary</dd>
                                </dl>                 
                                <div class="commands">
                                    @grid.EditButton(item)
                                    @grid.DeleteButton(item)                                    
                                </div>               
                            </div>
                         </text>)
                .DataBinding(dataBinding => dataBinding.Ajax()
                        .Select("_Sorting", "Trip")
                         .Insert("Create", "Trip")
                         .Update("Edit", "Trip")
                         .Delete("Delete", "Trip")
                            )
            .Sortable()
      )
*@